//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.04.29 at 11:55:48 AM BST
//

package uk.gov.ons.ctp.response.party.definition;

import javax.xml.bind.annotation.XmlRegistry;
import libs.party.definition.Enrolment;
import libs.party.definition.PartyCreationRequestAttributesDTO;
import libs.party.definition.PartyCreationRequestDTO;
import libs.party.definition.SampleLinkCreationRequestDTO;

/**
 * This object contains factory methods for each Java content interface and Java element interface
 * generated in the uk.gov.ons.ctp.response.party.definition package.
 *
 * <p>An ObjectFactory allows you to programatically construct new instances of the Java
 * representation for XML content. The Java representation of XML content can consist of schema
 * derived interfaces and classes representing the binding of schema type definitions, element
 * declarations and model groups. Factory methods for each of these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes
   * for package: uk.gov.ons.ctp.response.party.definition
   */
  public ObjectFactory() {}

  /** Create an instance of {@link PartyCreationRequestDTO } */
  public PartyCreationRequestDTO createPartyCreationRequestDTO() {
    return new PartyCreationRequestDTO();
  }

  /** Create an instance of {@link PartyCreationRequestAttributesDTO } */
  public PartyCreationRequestAttributesDTO createPartyCreationRequestAttributesDTO() {
    return new PartyCreationRequestAttributesDTO();
  }

  /** Create an instance of {@link SampleLinkCreationRequestDTO } */
  public SampleLinkCreationRequestDTO createSampleLinkCreationRequestDTO() {
    return new SampleLinkCreationRequestDTO();
  }

  /** Create an instance of {@link uk.gov.ons.ctp.response.party.definition.Association } */
  public uk.gov.ons.ctp.response.party.definition.Association createAssociation() {
    return new Association();
  }

  /** Create an instance of {@link Enrolment } */
  public Enrolment createEnrolment() {
    return new Enrolment();
  }
}
