//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.04.29 at 11:55:48 AM BST
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ons.gov.uk/ctp/response/party/definition")
package uk.gov.ons.ctp.response.party.definition;
