env: minikube
namespace: minikube

replicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

image:
  devRepo: eu.gcr.io/ons-rasrmbs-management
  name: eu.gcr.io/ons-rasrmbs-management
  tag: latest
  pullPolicy: Always

database:
  managedPostgres: false
  sqlProxyEnabled: false
  secrets:
    usernameKey: username
    passwordKey: password
    nameKey: db-name
  managedRedis: false

container:
  port: 8080
service:
  port: 8080

resources:
  requests:
    memory: "512Mi"

sftp:
  directory:
    business: /home/demo/sftp/BSD/
    documents: /home/demo/sftp/
  cron: "* * * * * ?"
  test:
    enabled: true

managedRabbitMQ:
  enabled: false

cron:
  kubernetesEnabled: false
  kubernetesCron: "@300"
  springCron: "0 0/5 * * * ?"

dns:
  enabled: false
  wellKnownPort: 8080