env: minikube
namespace: minikube

image:
  devRepo: eu.gcr.io/ons-rasrmbs-management
  name: eu.gcr.io/ons-rasrmbs-management
  tag: latest
  pullPolicy: Always

database:
  managedPostgres: false
  sqlProxyEnabled: false
  secrets:
    usernameKey: username
    passwordKey: password
    nameKey: db-name

container:
  port: 8080
service:
  port: 8080

resources:
  application:
    requests:
      memory: "512Mi"
      cpu: "400m"
    limits:
      memory: "1500Mi"
      cpu: "1000m"
  proxy:
    requests:
      memory: "25Mi"
      cpu: "10m"
    limits:
      memory: "64Mi"
      cpu: "100m"

autoscaling: false
scaleAt:
  # These are expressed as a percentage of resources.requests, not resources.limits
  memoryPercentage: 300
  cpuPercentage: 200
replicas: 1
maxReplicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

managedRabbitMQ:
  enabled: false

distribution:
  delay: 1000

dns:
  enabled: false
  wellKnownPort: 8080

gcp:
  project: ras-rm-sandbox
  sampleSummaryActivationSubscription: "sample-summary-activation-subscription"
  sampleSummaryActivationStatusTopic: "sample-summary-activation-status-topic"
  caseNotificationTopic: "case-notification-topic"