apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sample-export
spec:
  schedule: "{{ .Values.cron }}"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl
            image: curlimages/curl:7.71.0
            command: ["/bin/sh", "-c"]
            args:
              - |
                curl -X POST "http://{{ .Chart.Name }}:{{ .Values.dns.wellKnownPort }}/export" -H "accept: application/json"
          restartPolicy: OnFailure
      backoffLimit: 5
