@startuml
actor user
user -> IDBR: export sample
user -> ResponseOpsUI: upload sample CSV
ResponseOpsUI -> Sample:POST CSV
Sample -> Sample: validate sample against ruleset
Sample -> Sample: unmarshal to object tree (sample type specific)
Sample -> DB: persist sample
loop for each sample unit
  Sample -> RabbitMQ: enqueue
  Party -> RabbitMQ: Read Sample Unit
  Party -> DB: Process and Store
  Party -> RabbitMQ: enqueue recept (SampleUnitUUID)
  Sample -> update Sample Unit to DELIVERED
end
Sample -> DB: update Sample Summary state to ACTIVE
@enduml
