@startuml
actor user
IDBR -> user : export sample
user -> ResponseOpsUI: upload sample CSV
ResponseOpsUI -> SampleFileUploader :POST CSV
SampleFileUploader -> Sample: Create sample summary
loop for each sample unit
SampleFileUploader -> CSVWorker: send single line of sample file
CSVWorker -> Sample: Create sample with INIT state
Sample -> Sample : update Sample Unit to PERSISTED
CSVWorker -> Party: Create party and attribute
end
ResponseOpsUI -> Sample: check all units have been loaded
Sample -> Sample: update Sample Summary state to ACTIVE
@enduml
