@startuml
skinparam state {
    BackgroundColor HoneyDew
}

[*] --> INIT
INIT --> PERSISTED : persisting [[https://github.com/ONSdigital/rm-sample-service/blob/master/src/main/java/uk/gov/ons/ctp/response/sample/service/impl/SampleServiceImpl.java#L201 *]]
PERSISTED --> DELIVERED : delivering [[https://github.com/ONSdigital/rm-sample-service/blob/master/src/main/java/uk/gov/ons/ctp/response/sample/scheduled/distribution/SampleUnitDistributor.java#L146 *]]
@enduml