@startuml
skinparam state {
    BackgroundColor HoneyDew
}

[*] --> INIT
INIT --> ACTIVE : activated
ACTIVE --> FAILED : fail_validation
ACTIVE --> COMPLETE : completed
ACTIVE --> FAILED: fail_ingestion
@enduml